[build]
  publish = "public"
  command = "gatsby build"

[build.environment]
  GOOGLE_ANALYTICS = "UA-141926834-2"

[context.production]

[context.production.environment]
  GOOGLE_ANALYTICS = "UA-141926834-1"